.PHONY: clean All

All:
	@echo "----------Building project:[ UOCRailway - Test ]----------"
	@"$(MAKE)" -f  "UOCRailway.mk"
clean:
	@echo "----------Cleaning project:[ UOCRailway - Test ]----------"
	@"$(MAKE)" -f  "UOCRailway.mk" clean
